
services:
  frontend:
    build:
      context: .
      target: production
    container_name: scm-frontend
    expose:
      - "3000"
    environment:
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
    restart: always
    networks:
      - patindesa-network

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: scm-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - frontend
networks:
  patindesa-network:
    external: true